<<<<<<< HEAD
# Configuración básica para el sitio de cursos
title: "Cursos de Ingeniería"
author: "Prof. Rubén Velázquez Hernández"
description: "Recursos didácticos para cursos universitarios de Ingeniería"
baseurl: ""
url: ""

# Configuración de temas
theme: just-the-docs

# Configuración específica de Just The Docs
color_scheme: light
search_enabled: true
heading_anchors: true
aux_links:
  "Universidad Tecnológica de Querétaro":
    - "https://www.uteq.edu.mx/"
=======
# Configuración del sitio
title: Materiales Didácticos UTEQ
description: Repositorio de materiales didácticos para cursos de ingeniería
baseurl: "/PreparacionCursos"
url: "https://neburok.github.io"

# Configuración del tema Just the Docs
remote_theme: just-the-docs/just-the-docs
theme: just-the-docs
color_scheme: light

# Configuración de búsqueda
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Aux links para la navegación superior derecha
aux_links:
  "Ver en GitHub":
    - "//github.com/neburok/PreparacionCursos"
>>>>>>> ac32365c89f8a3a1911f608dc2d04e5784f7ac05

# Configuración del logo
# Para usar el logo optimizado cuando lo generes:
# logo: "/assets/images/logos/logo_small.png"
logo: "/assets/images/logo_UTEQ_color.png"
logo_alt: "Logo UTEQ"
# Control adicional para el logo
nav_external_links_custom_icons: true

<<<<<<< HEAD
# Configuración de navegación de Just the Docs
aux_links_new_tab: true
nav_sort: case_sensitive
back_to_top: true
back_to_top_text: "Volver arriba"
footer_content: "Copyright &copy; 2024 Universidad Tecnológica de Querétaro."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Configuración de colecciones para organizar cursos
=======
# Configuración de colecciones
>>>>>>> ac32365c89f8a3a1911f608dc2d04e5784f7ac05
collections:
  cursos:
    output: true
    permalink: /:collection/:name/
  materiales:
    output: true
    permalink: /:collection/:name/

<<<<<<< HEAD
=======
# Orden de navegación por defecto
nav_sort: case_sensitive

# Back to top link
back_to_top: true
back_to_top_text: "Volver arriba"

# Footer content
footer_content: "Copyright &copy; 2025 UTEQ. Distribuido bajo licencia CC BY-NC-SA 4.0."

# Configuración de Just the Docs
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

>>>>>>> ac32365c89f8a3a1911f608dc2d04e5784f7ac05
# Configuración por defecto
defaults:
  - scope:
      path: ""
      type: "cursos"
    values:
      layout: "curso"
  - scope:
      path: ""
      type: "materiales"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins de Jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
# Excluir archivos y carpetas
exclude:
  - .git/
  - .gitignore
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - resize_logo.html

# Variables personalizadas
<<<<<<< HEAD
institucion: "Universidad Tecnológica de Querétaro" 
=======
institucion: "Universidad Tecnológica de Querétaro"
>>>>>>> ac32365c89f8a3a1911f608dc2d04e5784f7ac05
